name: tiara_nxt_nconnect
description: Tiara Nxt nconnect API.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  shared_preferences: ^2.0.17
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.tiara_nxt.tiara_nxt_nconnect
        pluginClass: TiaraNxtNConnectPlugin
      ios:
        pluginClass: TiaraNxtNConnectPlugin
